# Generated by Django 4.1.1 on 2022-09-25 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(default=datetime.datetime.today, verbose_name='创建时间'),
        ),
    ]
